version: '3'
services:
  myjellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: myjellyfin
    ports:
      - "8096:8096"
    volumes:
      - jellyfin-cache:/cache:Z
      - jellyfin-config:/config:Z
      - /home/cryptomind/Music:/Music:ro
      - /home/cryptomind/Drama2:/Drama2:ro
      - /home/cryptomind/DramaKR:/DramaKR:ro
      - /home/cryptomind/Movies:/Movies:ro
      - /home/cryptomind/Shows2:/Shows2:ro
      - /home/cryptomind/ShowsKR2:/ShowsKR2:ro
      - /home/cryptomind/Youtube:/Youtube:ro
    user: "${UID}:${GID}"
    labels:
      - "io.containers.autoupdate=registry"
    networks:
      - default
    restart: unless-stopped # This corresponds to `--rm`
volumes:
  jellyfin-cache:
  jellyfin-config:
